### PR TITLE
add nodepool and uniteddeployment api

### PR DESCRIPTION
**Pull request by kadisi**
### Ⅰ. Describe what this PR does

ref: #171 

add an nodepool and uniteddeployment api.  

yurtapp-manager is a kubernetes operator for nodepool and uniteddeployment.

### Ⅴ. Special notes for reviews

@Fei-Guo @charleszheng44

### CODE REVIEW

**Review by Fei-Guo — COMMENTED** [review]
It seems that you choose `unit` as group name which seems to be confusing. How about just use `apps` as group name?
Also, how about rename yurtunit-manager to yurt-app-manager (we may have yurt-device-manager in the future).

**Comment by kadisi** [comment]
> It seems that you choose `unit` as group name which seems to be confusing. How about just use `apps` as group name?
> Also, how about rename yurtunit-manager to yurt-app-manager (we may have yurt-device-manager in the future).

@Fei-Guo good idea

**Comment by kadisi** [comment]
> It seems that you choose `unit` as group name which seems to be confusing. How about just use `apps` as group name?
> Also, how about rename yurtunit-manager to yurt-app-manager (we may have yurt-device-manager in the future).

good idea

**Comment by kadisi** [comment]
@Fei-Guo PTAL

**Review by Fei-Guo — APPROVED** [review]
Thanks for addressing the comments.

**Pull request merged**
